apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
  labels:
    app: conversao-temperatura
spec:
  selector:
    app: conversao-temperatura
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
